### Test the API completely without parameter (fetches ALL materials and calculates)
GET http://localhost:4004/margin-analysis/analyze
Accept: application/json
Authorization: Basic alice:alice

---

### The API has been migrated to a REST-based GET query 
### Filtering by Material 'MZ-FG-C990'
GET http://localhost:4004/margin-analysis/analyze?material=MZ-FG-C990
Accept: application/json
Authorization: Basic alice:alice

---

### Teste Filtrando um Material Específico (TG11)
GET http://localhost:4004/margin-analysis/analyze?material=TG11
Accept: application/json
Authorization: Basic alice:alice

---

### Mock Mode with multiple filters
GET http://localhost:4004/margin-analysis/analyze?material=MAT-1000&periodStart=2024-01&periodEnd=2024-06&plant=1000&mock=true
Accept: application/json
Authorization: Basic alice:alice
